medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: warehouse_user
      pass: warehouse_pass
      port: 5432
      dbname: medical_warehouse
      schema: public
      threads: 4
