medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      pass: postgres
      port: 5433
      dbname: medical_warehouse
      schema: public  # Default schema for dbt
      threads: 1
