version: 2

models:
  - name: dim_channels
    description: "Dimension table for Telegram channels"
    columns:
      - name: channel_key
        description: "Surrogate key for channel"
        tests:
          - unique
          - not_null
      - name: channel_name
        description: "Name of the Telegram channel"
      - name: channel_type
        description: "Type of channel (Medical, Cosmetics, Pharmaceutical)"
      - name: total_posts
        description: "Total number of posts from this channel"
        
  - name: dim_dates
    description: "Date dimension table for time-based analysis"
    columns:
      - name: date_key
        description: "Surrogate key for date (YYYYMMDD)"
        tests:
          - unique
          - not_null
      - name: full_date
        description: "Full date"
      - name: is_weekend
        description: "Boolean indicating if date is weekend"
        
  - name: fct_messages
    description: "Fact table for Telegram messages"
    columns:
      - name: message_id
        description: "Original message ID from Telegram"
        tests:
          - unique
          - not_null
      - name: channel_key
        description: "Foreign key to dim_channels"
        tests:
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        description: "Foreign key to dim_dates"
        tests:
          - relationships:
              to: ref('dim_dates')
              field: date_key
      - name: view_count
        description: "Number of views on the message"
      - name: forward_count
        description: "Number of forwards of the message"
